### ISSUE TITLE
GCP Cloud Functions Failure

### ISSUE THREAD

**Issue by dragonkhoi** [oelin/node-replicate#3]
Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/xxx/Documents/git/yyyy/server/functions/node_modules/node-replicate/src/index.js
require() of ES modules is not supported.
require() of /Users/xxxx/Documents/git/yyyy/server/functions/node_modules/node-replicate/src/index.js from /Users/xxxx/Documents/git/yyyy/server/functions/lib/services/replicate-api.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/xxxx/Documents/git/fanhouse-website/server/functions/node_modules/node-replicate/package.json.

Probably something to do with typescript or ESLint....?

**Comment by oelin** [comment]
It sounds like you might have tried to `require()` node-replicate, however only `import` is supported since it's an ES module.

**Comment by dragonkhoi** [comment]
Nope, I used import. Very strange.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/16108916/227791147-adb1e5a2-f97b-4435-925b-0a900173e173.png">
