### ISSUE TITLE
Invalid TYPES package

### ISSUE THREAD

**Issue by manelcomiche** [oelin/node-replicate#5]
It seems that the @types package of this package is invalid and does not recognise the RUN, is there a solution?

**Comment by oelin** [comment]
Yes the @types package created by another user is out of date with the current API. Will try to get that sorted out soon.

**Comment by manelcomiche** [comment]
Is there a quick solution? Do you think you can make a .d.ts yourself?

Thanks!

**Comment by oelin** [comment]
Will update the types package when I have time.
