### ISSUE TITLE
Why is it returning me this error?

### ISSUE THREAD

**Issue by scholly96** [oelin/node-replicate#7]
return fetch(`https://replicate.com/api/models${prediction.version.model.absolute_url}/versions/${prediction.version_id}/predictions/${prediction.uuid}`)
                                                                                   ^

TypeError: Cannot read properties of undefined (reading 'model')

**Comment by oelin** [comment]
Could you provide more context?

**Comment by sromovskypeter** [comment]
I use `midjourney-client` and I can see the same error for any request I make.

**Comment by yeci226** [comment]
> Could you provide more context?

When using
```
const model = "owner/model:version"
const input = { prompt: "an astronaut riding on a horse" }

await replicate. run(model, input)
```
will return this error
`TypeError: Cannot read properties of undefined (reading 'model')`

**Comment by bunpro1920** [comment]
i have same error and i found bug here

 {
  detail: 'You need to sign in to run this model.',
  code: 'SIGN_IN_REQUIRED'
}

**Comment by oelin** [comment]
Ah, yes some models are not possible to run from this client because they require authorization. May potentially add support for them in the future. On Replicate.com, you can check if a model requires sign in.

**Comment by bunpro1910** [comment]
Do you have any model for midjourney don't need sign in

**Comment by oelin** [comment]
Check out [midjourney-client](https://npmjs.com/midjourney-client) which uses Openjourney.

**Comment by scholly96** [comment]
> Ah, yes some models are not possible to run from this client because they require authorization. May potentially add support for them in the future. On Replicate.com, you can check if a model requires sign in.

Is there a daily limit? or can i use it at will?

**Comment by sromovskypeter** [comment]
There is the same problem with midjourney-client.

**Comment by oelin** [comment]
> > Ah, yes some models are not possible to run from this client because they require authorization. May potentially add support for them in the future. On Replicate.com, you can check if a model requires sign in.
> 
> Is there a daily limit? or can i use it at will?

There's potentially a limit, however Replicate.com don't seem to specify it anywhere.

**Comment by halower** [comment]
In Windows, the application is actually working properly, so I feel like it's related to the operating system.

**Comment by yeci226** [comment]
> In Windows, the application is actually working properly, so I feel like it's related to the operating system.

Same, this error apeared when i using linux

**Comment by halower** [comment]
I have solved this problem, it should be an issue with the library. Great job!

**Comment by yeci226** [comment]
> I have solved this problem, it should be an issue with the library. Great job!

how to solve?

**Comment by halower** [comment]
There's potentially a limit, however Replicate.com don't seem to specify it anywhere, use Stable Diffusion local api

**Comment by sromovskypeter** [comment]
It does work with some of the VPN servers (Proton). But, I have definitely not hit the limit with my IP address. Online prompt at PromptHero works always fine.

**Comment by oelin** [comment]
> > Could you provide more context?
> 
> When using
> 
> ```
> const model = "owner/model:version"
> const input = { prompt: "an astronaut riding on a horse" }
> 
> await replicate. run(model, input)
> ```
> 
> will return this error `TypeError: Cannot read properties of undefined (reading 'model')`

I realise that this might have not been clear enough, but you'll need to pass in a concrete model name and version id. For instance, `stability-ai/stable-diffusion:db21e45d3f7023abc2a46ee38a23973f6dce16bb082a930b0c49861f96d1e5bf`.

**Comment by halower** [comment]
> > Could you provide more context?
> 
> When using
> 
> ```
> const model = "owner/model:version"
> const input = { prompt: "an astronaut riding on a horse" }
> 
> await replicate. run(model, input)
> ```
> 
> will return this error `TypeError: Cannot read properties of undefined (reading 'model')`
I forgot to explain to you in detail. I have rewritten the logic of this section, but in fact, I found that the official website will record your IP address. When the frequency of requests is too high, an exception of 400-403 will be triggered. Therefore, I used a dynamic proxy, a free proxy crawled by the website I found online
@yeci226

**Comment by BarryAllen-Arrow** [comment]
I'm having the TypeError: Cannot read properties of undefined (reading 'model') issue even using “no need to sign in” models(already test it with the openjourney model).... Have no idea why :(

**Comment by sromovskypeter** [comment]
I am still seeing the error. I don't understand why would you close this issue without any explanation.
