### ISSUE TITLE
Why am I getting this error?

### ISSUE THREAD

**Issue by 0x72616661656C** [oelin/node-replicate#8]
```
const prediction = await replicate.default.model(
                "prompthero/openjourney:9936c2001faa2194a261c01381f90e65261879985476014a0a37a334593a05eb",
            )
            .predict({
                prompt: prompt,
            });
```

TypeError: replicate.default.model is not a function

**Comment by oelin** [comment]
The current API does not use `model`. Use `replicate.run("prompthero/openjourney:9936c2001faa2194a261c01381f90e65261879985476014a0a37a334593a05eb", { prompt })` instead.

**Comment by 0x72616661656C** [comment]
`TypeError: replicate.run is not a function`

again
